version: "3"
services:
  mysql:
    image: mariadb:10.11
    container_name: snipeit-db
    restart: always
    volumes:
      - ./snipe_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=snipeit
      - MYSQL_DATABASE=snipeit_db
      - TZ=Asia/Bangkok
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1

    depends_on:
      - mysql
    volumes:
      - ./snipe_it:/config
    environment:
      - APP_URL=http://localhost:8080
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipeit_db
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=snipeit
      - TZ=Asia/Bangkok
      - PGID=1000
      - PUID=1000
    ports:
      - "8080:80"